In [2]:
import numpy as np
import pandas as pd

In [3]:

df = pd.read_csv("heart.csv")

In [4]:

df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [5]:
df = df.rename(columns={
    "Age": "age",
    "Sex": "sex",
    "ChestPainType": "cp",
    "RestingBP": "trestbps",
    "Cholesterol": "chol",
    "FastingBS": "fbs",
    "RestingECG": "restecg",
    "MaxHR": "thalach",
    "ExerciseAngina": "exang",
    "Oldpeak": "oldpeak",
    "ST_Slope": "slope",
    "HeartDisease": "target"
})

In [6]:
# sex
df["sex"] = df["sex"].map({"M": 1, "F": 0})

# chest pain
df["cp"] = df["cp"].map({
    "ATA": 1,
    "NAP": 2,
    "ASY": 0,
    "TA": 3
})

# restecg
df["restecg"] = df["restecg"].map({
    "Normal": 0,
    "ST": 1,
    "LVH": 2
})

# exercise angina
df["exang"] = df["exang"].map({"N": 0, "Y": 1})

# slope
df["slope"] = df["slope"].map({
    "Up": 2,
    "Flat": 1,
    "Down": 0
})

In [7]:
df["ca"] = 0
df["thal"] = 0

In [8]:
df = df[[
    "age","sex","cp","trestbps","chol","fbs","restecg",
    "thalach","exang","oldpeak","slope","ca","thal","target"
]]

In [9]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,40,1,1,140,289,0,0,172,0,0.0,2,0,0,0
1,49,0,2,160,180,0,0,156,0,1.0,1,0,0,1
2,37,1,1,130,283,0,1,98,0,0.0,2,0,0,0
3,48,0,0,138,214,0,0,108,1,1.5,1,0,0,1
4,54,1,2,150,195,0,0,122,0,0.0,2,0,0,0

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [11]:

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [12]:

clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [13]:

clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\03-11-24\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [14]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.8586956521739131
Accuracy of Decision Trees 0.7554347826086957

In [16]:
confusion_matrix(y_test,y_pred1)

array([[74, 15],
       [11, 84]], dtype=int64)

In [17]:

print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix

    0   1
0  74  15
1  11  84

In [18]:

print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix

    0   1
0  65  24
1  21  74

In [19]:

result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [20]:

result.sample(10)

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
581             1                               1                         1
695             1                               1                         1
451             1                               1                         1
508             1                               1                         1
526             1                               1                         1
851             0                               0                         1
382             1                               1                         1
687             0                               0                         0
563             1                               1                         1
686             0                               0                         1

In [21]:

from sklearn.metrics import recall_score,precision_score,f1_score

In [22]:

print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  74  15
1  11  84
--------------------------------------------------
Precision -  0.8484848484848485
Recall -  0.8842105263157894
F1 score -  0.865979381443299

In [23]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
    0   1
0  65  24
1  21  74
--------------------------------------------------
Precision -  0.7551020408163265
Recall -  0.7789473684210526
F1 score -  0.7668393782383419

In [24]:

precision_score(y_test,y_pred1,average=None)

array([0.87058824, 0.84848485])

In [25]:

precision_score(y_test,y_pred2,average=None)

array([0.75581395, 0.75510204])

In [26]:

recall_score(y_test,y_pred2,average=None)

array([0.73033708, 0.77894737])