In [5]:
import pandas as pd 
import numpy as np

In [7]:
df = pd.read_csv('mnist.csv')

In [8]:

df.head()

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=2)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [11]:

clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [12]:

clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\03-11-24\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [13]:

y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [14]:

from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.888
Accuracy of Decision Trees 0.815

In [15]:

print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix

     0    1    2    3    4    5    6    7    8    9
0  206    0    1    1    0    6    0    0    0    1
1    0  231    2    1    0    1    0    3    1    0
2    1    0  182    4    0    2    4    4   10    2
3    0    0    4  168    0    8    0    1    5    0
4    1    0    3    2  166    1    3    2    3    8
5    1    0    2   13    2  123    2    2   13    4
6    3    1    3    0    2    6  180    1    0    0
7    2    2    7    3    3    1    0  202    2    3
8    1    1    8    7    0    9    4    0  156    8
9    1    0    4    4    9    1    0    3    1  162

In [16]:

print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix

     0    1    2    3    4    5    6    7    8    9
0  183    0    6    3    2    5    7    0    5    4
1    0  221    2    1    1    4    1    2    6    1
2    1    0  161    8    7    4    5   10   10    3
3    0    1    1  167    1   11    0    0    4    1
4    3    3    2    2  150    4    5    1    4   15
5    6    2    2    8    4  122    3    1    7    7
6    5    2    4    2    5    6  158    1   10    3
7    1    1    8    5    9    1    3  186    2    9
8    3    3    5   10    7    6    2    9  141    8
9    1    2    1    5   19    2    1    5    8  141

In [17]:

from sklearn.metrics import precision_score,recall_score,f1_score

In [18]:
precision_score(y_test,y_pred1,average='weighted')

0.8888294791750739

In [19]:

recall_score(y_test,y_pred1,average='weighted')

0.888

In [20]:

f1_score(y_test,y_pred1,average='weighted')

0.8881470593507418

In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       215
           1       0.98      0.97      0.97       239
           2       0.84      0.87      0.86       209
           3       0.83      0.90      0.86       186
           4       0.91      0.88      0.89       189
           5       0.78      0.76      0.77       162
           6       0.93      0.92      0.93       196
           7       0.93      0.90      0.91       225
           8       0.82      0.80      0.81       194
           9       0.86      0.88      0.87       185

    accuracy                           0.89      2000
   macro avg       0.88      0.88      0.88      2000
weighted avg       0.89      0.89      0.89      2000